//
// Created by Iason Andronis on 2023-12-27.
//

#ifndef ADVENT_OF_CODE_DAY_2_CUBE_CONUNDRUM_CUBE_CONUNDRUM_H
#define ADVENT_OF_CODE_DAY_2_CUBE_CONUNDRUM_CUBE_CONUNDRUM_H

#endif //ADVENT_OF_CODE_DAY_2_CUBE_CONUNDRUM_CUBE_CONUNDRUM_H
